# DOCKERFILE: RECEITA PARA RODAR MEU APP EM QUALQUER LUGAR
# RECEITA DE COMO CONSTRUIR A 'IMAGEM' DO MEU APP
FROM node:16-alpine

COPY . /app

WORKDIR /app

RUN npm install

EXPOSE $PORT

ENTRYPOINT ["npm", "start"]